### ISSUE TITLE
Latest commits breaks ghost

### ISSUE THREAD

**Issue by JaneJeon** [SNathJr/ghost-on-heroku#14]
Error: Cannot find module './node_modules/ghost/core/server/services/url'

caused by ccef87e - when I run `ls node_modules/ghost/core/server/services`, I only see:

`apps  invitations  mail     permissions  slack.js  xmlrpc.js
auth  labs.js      members  settings     webhooks` (and this is after I ran `npm install --production` again)

**Comment by SNathJr** [comment]
@JaneJeon Thank you for creating an issue. It was a rouge commit and it has been fixed now. I as pushing some old commits from local machine, when this happened. 

I will be closing this issue now. If you have further questions, please feel free to reopen and comment.

Thank you again.
